module RadCommon
  class Engine < ::Rails::Engine
    config.generators do |g|
      g.test_framework :rspec
      g.fixture_replacement :factory_girl, dir: 'spec/factories'
    end

    require 'active_storage_validations'
    require 'audited'
    require 'authtrail'
    require 'csv'
    require 'devise'
    require 'devise-twilio-verify'
    require 'devise-security'
    require 'devise_invitable'
    require 'faker'
    require 'faraday'
    require 'geocoder'
    require 'omniauth-google-oauth2'
    require 'haml-rails'
    require 'hashids'
    require 'jwt'
    require 'kaminari'
    require 'bootstrap4-kaminari-views'
    require 'nokogiri'
    require 'pg'
    require 'prawn'
    require 'prawn/table'
    require 'premailer/rails'
    require 'pretender'
    require 'pundit'
    require 'rack/attack'
    require 'sendgrid-ruby'
    require 'sentry-rails'
    require 'sentry-ruby'
    require 'sidekiq'
    require 'sidekiq/web'
    require 'simple_form'
    require 'smartystreets_ruby_sdk'
    require 'strip_attributes'
    require 'text'
    require 'turbo-rails'
    require 'twilio-ruby'
    require 'wicked_pdf'
  end
end
