development:
  adapter: postgresql
  encoding: unicode
  database: rad_common_development
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: rad_common_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: postgres
  password: postgres
  host: localhost

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || 10 %>
