development:
  adapter: postgresql
  encoding: unicode
  database: rad_common_development

test:
  adapter: postgresql
  encoding: unicode
  database: rad_common_test

production:
  adapter: postgresql
  encoding: unicode
  database: rad_common_production
