development:
  adapter: postgresql
  encoding: unicode
  database: rad_common_development

test:
  adapter: postgresql
  encoding: unicode
  database: rad_common_test

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || 10 %>
