development:
  adapter: postgresql
  encoding: unicode
  database: rad_common_development

test:
  adapter: postgresql
  encoding: unicode
  database: rad_common_test
  username: postgres
  password: postgres
  host: localhost

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || 10 %>
