name: RSpec Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  RAILS_ENV: test
  CI: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - TEST_ENV_NUMBER: 1
            GROUP: '1,2'
          - TEST_ENV_NUMBER: 2
            GROUP: '3,4'

    env:
      TEST_ENV_NUMBER: ${{ matrix.TEST_ENV_NUMBER }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rad_common_test${{ matrix.TEST_ENV_NUMBER }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Running custom steps
        uses: ./.github/actions/custom-action
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.set-ruby-version.outputs.version }}
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '16.20.2'
          cache: 'yarn'

      - name: Yarn install
        working-directory: spec/dummy
        run: yarn install

      - name: Prepare database
        working-directory: spec/dummy
        run: |
          bundle exec rails db:test:prepare

      - name: Cache Webpacker packs
        uses: actions/cache@v4
        with:
          path: |
            public/packs
            public/packs-test
            node_modules
          key: ${{ runner.os }}-webpacker-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-webpacker-

      - name: Compile Webpacker assets
        working-directory: spec/dummy
        run: bundle exec rails webpacker:compile

      - name: Update webdrivers
        working-directory: spec/dummy
        run: bundle exec rake webdrivers:chromedriver:update

      - name: Load schema
        working-directory: spec/dummy
        run: bundle exec rake parallel:load_schema

      - name: Run RSpec tests
        run: |
          bundle exec parallel_rspec spec --exclude-pattern 'templates/rspec/*.*' -n 4 --only-group ${{ matrix.GROUP }}
